services:
  app:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    tty: true
    init: true
    volumes:
      - .:/root/app
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    networks:
      - default_network

  db:
    platform: linux/x86_64
    image: mysql:5.7
    hostname: mysql
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./storage/log/db:/var/log/mysql
    ports:
      - 3300:3306
    env_file:
      - .env.dev
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
