"""first

Revision ID: d028a86988dd
Revises:
Create Date: 2022-05-09 17:50:27.984994

"""
# flake8: ignore
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d028a86988dd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True, comment="顧客ID"),
        sa.Column("is_admin", sa.Boolean(), nullable=True, comment="管理者か"),
        sa.Column("name", sa.String(length=50), nullable=False, comment="名前"),
        sa.Column("email", sa.String(length=50), nullable=False, comment="メールアドレス"),
        sa.Column("remark", sa.Text(), nullable=False, comment="備考"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="作成日時"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新日時"),
        sa.PrimaryKeyConstraint("id"),
        comment="ユーザー",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
