version: 2.1

executors:
  ubuntu:
    machine:
      image: ubuntu-2004:current
  python:
    docker:
      - image: cimg/python:3.9.16

jobs:
  setup:
    executor: python
    shell: /bin/bash
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: poetryのインストール
          command: |
            pip install --upgrade pip && \
            pip install poetry && \
            poetry config virtualenvs.in-project true && \
            poetry config virtualenvs.create true
      - run:
          name: パッケージのインストール
          command: poetry install
      - run:
          name: 仮想環境に入る
          command: poetry shell
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    executor: python
    shell: /bin/bash
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: リント実行
          command: inv lint
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy-dev:
    executor: ubuntu
    shell: /bin/bash
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - add_ssh_keys
      - run:
          name: SSHで最新状態を適用
          command: >
            ssh ${USER_NAME}@${HOST_NAME} "cd ~/workspace/atd_00_template_api_python && ./scripts/deploy-develop.sh"
workflows:
  lint_deploy:
    jobs:
      - setup:
          filters:
            branches:
              ignore:
               - main
               - master
               - develop
      - lint:
          requires:
            - setup
          filters:
            branches:
              ignore:
                - main
                - master
                - develop
      - deploy-dev:
          filters:
            branches:
              only:
                - develop
