version: 2.1

executors:
  ubuntu:
    machine:
      image: ubuntu-2004:current
  python:
    docker:
      - image: cimg/python:3.9.16

jobs:
  setup:
    executor: ubuntu
    shell: /bin/bash
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: pwd
          command: pwd
      - run:
          name: ls
          command: ls
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: docker-compose ps
          command: docker-compose ps
      - run:
          name: docker-compose exec app bash
          command: docker-compose exec app bash
      - run:
          name: ls a
          command: ls
      # - run:
      #     name: 仮想環境に入る
      #     command: poetry shell
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    executor: ubuntu
    shell: /bin/bash
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: リント実行
          command: |
            docker-compose exec app bash poetry shell && \
            inv lint
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy-dev:
    executor: ubuntu
    shell: /bin/bash
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - add_ssh_keys
      - run:
          name: SSHで最新状態を適用
          command: >
            ssh ${USER_NAME}@${HOST_NAME} "cd ~/workspace/atd_00_template_api_python && ./scripts/deploy-develop.sh"
workflows:
  lint_deploy:
    jobs:
      - setup:
          filters:
            branches:
              ignore:
               - main
               - master
               - develop
      - lint:
          requires:
            - setup
          filters:
            branches:
              ignore:
                - main
                - master
                - develop
      - deploy-dev:
          filters:
            branches:
              only:
                - develop
